version: "3.9"

services:
  backend:
    platform: linux/x86_64
    build: .
    container_name: k1-backend
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: postgres:alpine3.17
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  frontend:
    container_name: k1-frontend
    build: ./frontend
    ports:
      - 80:3001

volumes:
  db_data:
  bundle:
