default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kodone_backend_development

test:
  <<: *default
  database: kodone_backend_test

production:
  <<: *default
  database: kodone_backend_production
  username: kodone_backend
  password: <%= Rails.application.credentials.dig(:database, :password) %>
